default_platform(:android)

platform :android do
  desc "Сборка и публикация в Google Play"
  lane :deploy do
    gradle(
      task: "bundle",
      build_type: "Release",
      flavor: "prod"
    )

    upload_to_play_store(
      track: "internal",
      aab: "app/build/outputs/bundle/prodRelease/app-prod-release.aab",
      json_key: "app/play-account.json",
      package_name: "rees46.demo_shop"
    )
  end
end
