name: Publish to Play Store and Bump Version

on:
  push:
    branches:
      - master
      - stage

jobs:
  setup_google_services:
    runs-on: ubuntu-latest
    steps:

    build_release_apk:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Decode and create google-services.json
          run: |
            mkdir -p app/src/prod/release
            echo "$GOOGLE_SERVICES_JSON" | base64 -d > app/src/prod/release/google-services.json
            ls -la app/src/prod/release
          env:
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}

        - name: Decode Keystore
          run: |
            echo "$KEYSTORE_AS_BASE64" | base64 --decode > keystore.jks
            ls -lah keystore.jks
          env:
            KEYSTORE_AS_BASE64: ${{ secrets.KEYSTORE_AS_BASE64 }}


        - name: Set up JDK 20
          uses: actions/setup-java@v4
          with:
            java-version: '20'
            distribution: 'zulu'

        - name: Build Release APK
          run: ./gradlew assembleProdRelease
          env:
            SIGNING_STORE_FILE: keystore.jks
            SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
            SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
            SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

        - name: Upload APK
          uses: actions/upload-artifact@v4
          with:
            name: app-release
            path: app/build/outputs/apk/prod/release/app-prod-release.apk
