name: Build APK

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  build_release_apk:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/'))
    # TODO uncomment
    # uses: rees46/workflow/.github/workflows/reusable-android-release-apk.yaml@master
    uses: rees46/workflow/.github/workflows/reusable-android-release-apk.yaml@refactor/google-play-publish
    with:
      appId: ${{ vars.PUBLIVERSIONER_ID }}
    secrets:
      appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}
      googleServicesFileAsBase64: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}
      googlePlaySigningKeyFileAsBase64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY_FILE_AS_BASE64 }}
      releaseStorePassword: ${{ secrets.RELEASE_STORE_PASSWORD }}
      releaseKeyAlias: ${{ secrets.RELEASE_KEY_ALIAS }}
      releaseKeyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
