name: Build APK

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  build_release_apk:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/'))
    uses: rees46/workflow/.github/workflows/reusable-android-release-apk.yaml@master
    with:
      appId: ${{ vars.PUBLIVERSIONER_ID }}
    secrets:
      appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}
      googleServicesFileAsBase64: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}
      googlePlaySigningKeyFileAsBase64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY_FILE_AS_BASE64 }}
