name: Publish to Play Store and Bump Version

on:
  push:
    branches:
      - master
      - stage

jobs:
  publish_and_version_bump:
    uses: rees46/workflow/.github/workflows/reusable-android-google-play-publish.yaml@master
    with:
      packageName: "rees46.demo_shop"
      releaseFiles: "app/build/outputs/bundle/prodRelease/app-prod-release.aab"
      PROPERTIES_FILE: "version.properties"
    secrets:
      PLAY_ACCOUNT_AS_BASE64: ${{ secrets.PLAY_ACCOUNT_AS_BASE64 }}
      KEYSTORE_AS_BASE64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY_FILE_AS_BASE64 }}
      SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      GITHUB_APP_ID: ${{ vars.PUBLIVERSIONER_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.PUBLIVERSIONER_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode and create google-services.json
        run: |
          mkdir -p app/src/prod/release
          echo "${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}" | base64 --decode > app/src/prod/release/google-services.json
          ls -la app/src/prod/release
        env:
          GOOGLE_SERVICES_FILE_AS_BASE64: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}

      - name: Continue with reusable workflow
        uses: rees46/workflow/.github/workflows/reusable-android-google-play-publish.yaml@master
