name: Publish to Play Store and Bump Version

on:
  pull_request:
  # push:
  #   branches:
  #     - master

jobs:
  publish_and_version_bump:
    # uses: rees46/workflow/.github/workflows/reusable-android-google-play-publish.yaml@master
    # TODO uncomment
    uses: rees46/workflow/.github/workflows/reusable-android-google-play-publish.yaml@fix/inputs
    with:
      packageName: "rees46.demo_shop"
      releaseFiles: "app/build/outputs/bundle/prodRelease/app-prod-release.aab"
      PROPERTIES_FILE: "version.properties"
    secrets:
      PLAY_ACCOUNT_AS_BASE64: ${{ secrets.PLAY_ACCOUNT_AS_BASE64 }} # Google Play Auth for service account
      KEYSTORE_AS_BASE64: ${{ secrets.KEYSTORE_AS_BASE64 }} # Keystore for singing release bundle
      SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      GITHUB_APP_ID: ${{ vars.PUBLIVERSIONER_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.PUBLIVERSIONER_SECRET }}
      GOOGLE_SERVICES_FILE_AS_BASE64: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}
