name: Publish to Play Store and Bump Version

on:
  push:
    branches:
      - master
      - stage

jobs:
  setup_google_services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode and create google-services.json
        run: |
          mkdir -p app/src/prod/release
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > app/src/prod/release/google-services.json
          ls -la app/src/prod/release
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}

      - name: Upload google-services.json
        uses: actions/upload-artifact@v4
        with:
          name: google-services-json
          path: app/src/prod/release/google-services.json

  setup_signing_keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_AS_BASE64 }}" | base64 --decode > keystore.jks
          ls -lah keystore.jks

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: keystore.jks

  build_release_apk:
    runs-on: ubuntu-latest
    needs: [setup_google_services, setup_signing_keys]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download google-services.json
        uses: actions/download-artifact@v4
        with:
          name: google-services-json
          path: app/src/prod/release

      - name: Download Keystore
        uses: actions/download-artifact@v4
        with:
          name: keystore
          path: .

      - name: Build Release APK
        run: ./gradlew assembleProdRelease
        env:
          SIGNING_STORE_FILE: keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/prod/release/app-prod-release.apk
