name: Publish to Play Store and Bump Version

on:
  push:
    branches:
      - master

jobs:
  publish_and_version_bump:
    uses: rees46/workflow/.github/workflows/reusable-android-google-play-publish.yaml@master
    with:
      githubAppId: ${{ vars.PUBLIVERSIONER_ID }}
      packageName: "rees46.demo_shop"
      aabReleasePath: "app/build/outputs/bundle/prodRelease/app-prod-release.aab"
      propertiesFilePath: "version.properties"
    secrets:
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.PUBLIVERSIONER_SECRET }}
      GOOGLE_SERVICES_FILE_AS_BASE64: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}
      GOOGLE_PLAY_SIGNING_KEY_FILE_AS_BASE64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY_FILE_AS_BASE64 }}
      RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      PLAY_ACCOUNT_AS_BASE64: ${{ secrets.PLAY_ACCOUNT_AS_BASE64 }}
