name: Publish to Play Store and Bump Version

on:
  push:
    branches:
      - master
      - stage

jobs:
  build_release_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'zulu'

      # Building release apk
      - name: Build Release APK
        run: ./gradlew assembleProdRelease
        env:
          SIGNING_STORE_FILE: app/keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/prod/release/app-prod-release.apk

  publish_and_version_bump:
    uses: rees46/workflow/.github/workflows/reusable-android-google-play-publish.yaml@master
    with:
      packageName: "rees46.demo_shop"
      releaseFiles: "app/build/outputs/bundle/prodRelease/app-prod-release.aab"
      PROPERTIES_FILE: "version.properties"
    secrets:
      PLAY_ACCOUNT_AS_BASE64: ${{ secrets.PLAY_ACCOUNT_AS_BASE64 }}  # Google Play Auth for service account
      KEYSTORE_AS_BASE64: ${{ secrets.KEYSTORE_AS_BASE64 }}          # Keystore for singing release bundle
      SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      GITHUB_APP_ID: ${{ vars.PUBLIVERSIONER_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.PUBLIVERSIONER_SECRET }}
