name: Publish to Play Store and Bump Version

on:
  pull_request:
  # push:
  #   branches:
  #     - master

jobs:
  publish_and_version_bump:
    # # TODO uncomment
    # # uses: rees46/workflow/.github/workflows/reusable-android-google-play-publish.yaml@master
    # uses: rees46/workflow/.github/workflows/reusable-android-google-play-publish.yaml@fix/android-publish
    # with:
    #   packageName: "rees46.demo_shop"
    #   releaseFiles: "app/build/outputs/bundle/prodRelease/app-prod-release.aab"
    #   PROPERTIES_FILE: "version.properties"
    # secrets:
    #   PLAY_ACCOUNT_AS_BASE64: ${{ secrets.PLAY_ACCOUNT_AS_BASE64 }} # Google Play Auth for service account
    #   KEYSTORE_AS_BASE64: ${{ secrets.KEYSTORE_AS_BASE64 }} # Keystore for singing release bundle
    #   SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
    #   SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
    #   SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
    #   GITHUB_APP_ID: ${{ vars.PUBLIVERSIONER_ID }}
    #   GITHUB_APP_PRIVATE_KEY: ${{ secrets.PUBLIVERSIONER_SECRET }}
    #   GOOGLE_SERVICES_FILE_AS_BASE64: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current version from source
        env:
          FILE_PATH: "version.properties"
        id: version_source
        run: |
          current_version=$(awk -F"=" '/VERSION_NAME/ {print $2}' "$FILE_PATH")
          echo "version=$current_version" >> $GITHUB_OUTPUT

      - name: Decode and create google-services.json
        run: |
          mkdir -p app/src/prod/release
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > app/src/prod/release/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}

      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_AS_BASE64" | base64 --decode > app/keystore.jks
        env:
          KEYSTORE_AS_BASE64: ${{ secrets.GOOGLE_PLAY_SIGNING_KEY_FILE_AS_BASE64 }}

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: "20"
          distribution: "zulu"

      - name: Build Release APK
        run: ./gradlew bundleProdRelease
        env:
          SIGNING_STORE_FILE: ${{ github.workspace }}/app/keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
