name: Publish to Play Store and Bump Version

on:
  push:
    branches:
      - master

jobs:
  publish_and_version_bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GITHUB_APP_ID }}
          private-key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'zulu'

      - name: Create Keystore file
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks

      - name: Build Release AAB
        run: ./gradlew bundleProdRelease
        env:
          SIGNING_STORE_FILE: app/keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Deploy to Google Play Internal Testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: "rees46.demo_shop"
          releaseFiles: "app/build/outputs/bundle/prodRelease/app-prod-release.aab"
          track: "internal"

      - name: Bump version
        run: ./gradlew incrementVersion
        env:
          PROPERTIES_FILE: version.properties

      - name: Retrieve new version
        id: versionName
        run: |
          version=$(grep "VERSION_NAME=" version.properties | cut -d'=' -f2)
          echo "versionName=$version" >> $GITHUB_ENV
          echo "versionName=$version" >> $GITHUB_OUTPUT

      - name: Commit changes
        id: committer
        uses: planetscale/ghcommit-action@v0.1.44
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          repo: ${{ github.repository }}
          branch: master
          commit_message: 'chore: bump version to ${{ steps.versionName.outputs.versionName }}'
          file_pattern: 'version.properties'