name: Sync repositories

on:
  workflow_run:
    workflows:
      - "Publish to Play Store and Bump Version"
    types:
      - completed
  workflow_dispatch:

jobs:
  run:
    uses: rees46/workflow/.github/workflows/reusable-android-synchronization.yaml@master
    permissions: write-all
    secrets:
      token: ${{ secrets.JADE_SMITH_BOT_TOKEN }}
    with:
      targetRepository: personaclick/demo-android
