name: Sync repositories

on:
  workflow_run:
    workflows:
      - "Bump version, create release and publish"
    types:
      - completed
  workflow_dispatch:

jobs:
  run:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    # TODO change branch name to master
    uses: rees46/workflow/.github/workflows/reusable-android-synchronization.yaml@feat/android-sync
    permissions: write-all
    secrets:
      token: ${{ secrets.JADE_SMITH_BOT_TOKEN }}
